// Code generated by protoc-gen-ext. DO NOT EDIT.
// source: github.com/xdmybl/gate-type/proto/gate/v1/ca_certificate.proto

package v1

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"strings"

	"github.com/golang/protobuf/proto"
	equality "github.com/solo-io/protoc-gen-ext/pkg/equality"
)

// ensure the imports are used
var (
	_ = errors.New("")
	_ = fmt.Print
	_ = binary.LittleEndian
	_ = bytes.Compare
	_ = strings.Compare
	_ = equality.Equalizer(nil)
	_ = proto.Message(nil)
)

// Equal function
func (m *CaCertificateSpec) Equal(that interface{}) bool {
	if that == nil {
		return m == nil
	}

	target, ok := that.(*CaCertificateSpec)
	if !ok {
		that2, ok := that.(CaCertificateSpec)
		if ok {
			target = &that2
		} else {
			return false
		}
	}
	if target == nil {
		return m == nil
	} else if m == nil {
		return false
	}

	if h, ok := interface{}(m.GetCommonInfo()).(equality.Equalizer); ok {
		if !h.Equal(target.GetCommonInfo()) {
			return false
		}
	} else {
		if !proto.Equal(m.GetCommonInfo(), target.GetCommonInfo()) {
			return false
		}
	}

	if h, ok := interface{}(m.GetCertificateInfo()).(equality.Equalizer); ok {
		if !h.Equal(target.GetCertificateInfo()) {
			return false
		}
	} else {
		if !proto.Equal(m.GetCertificateInfo(), target.GetCertificateInfo()) {
			return false
		}
	}

	if strings.Compare(m.GetCa(), target.GetCa()) != 0 {
		return false
	}

	if strings.Compare(m.GetCrl(), target.GetCrl()) != 0 {
		return false
	}

	if m.GetAllowExpiredCertificate() != target.GetAllowExpiredCertificate() {
		return false
	}

	if h, ok := interface{}(m.GetTlsParameters()).(equality.Equalizer); ok {
		if !h.Equal(target.GetTlsParameters()) {
			return false
		}
	} else {
		if !proto.Equal(m.GetTlsParameters(), target.GetTlsParameters()) {
			return false
		}
	}

	if len(m.GetAlpnProtocols()) != len(target.GetAlpnProtocols()) {
		return false
	}
	for idx, v := range m.GetAlpnProtocols() {

		if strings.Compare(v, target.GetAlpnProtocols()[idx]) != 0 {
			return false
		}

	}

	return true
}
