// Code generated by engine gate build no edit

// This file contains generated Deepcopy methods for proto-based Spec and Status fields

package v1

import (
	proto "github.com/golang/protobuf/proto"
	"github.com/solo-io/protoc-gen-ext/pkg/clone"
)

// DeepCopyInto for the CaCertificate.Spec
func (in *CaCertificateSpec) DeepCopyInto(out *CaCertificateSpec) {
	var p *CaCertificateSpec
	if h, ok := interface{}(in).(clone.Cloner); ok {
		p = h.Clone().(*CaCertificateSpec)
	} else {
		p = proto.Clone(in).(*CaCertificateSpec)
	}
	*out = *p
}

// DeepCopyInto for the SslCertificate.Spec
func (in *SslCertificateSpec) DeepCopyInto(out *SslCertificateSpec) {
	var p *SslCertificateSpec
	if h, ok := interface{}(in).(clone.Cloner); ok {
		p = h.Clone().(*SslCertificateSpec)
	} else {
		p = proto.Clone(in).(*SslCertificateSpec)
	}
	*out = *p
}
