// Code generated by engine gate build no edit

// Definitions for the Kubernetes types
package v1

// CaCertificateSlice represents a slice of *CaCertificate
type CaCertificateSlice []*CaCertificate

// SslCertificateSlice represents a slice of *SslCertificate
type SslCertificateSlice []*SslCertificate
