// Code generated by engine gate build no edit

// Definitions for the Kubernetes types
package v1

// CaCertificateSlice represents a slice of *CaCertificate
type CaCertificateSlice []*CaCertificate

// SslCertificateSlice represents a slice of *SslCertificate
type SslCertificateSlice []*SslCertificate

// UpstreamSlice represents a slice of *Upstream
type UpstreamSlice []*Upstream

// GatewaySlice represents a slice of *Gateway
type GatewaySlice []*Gateway

// FilterSlice represents a slice of *Filter
type FilterSlice []*Filter
