// Code generated by engine gate build no edit

// Package v1 contains API Schema definitions for the gate.xdmybl.io v1 API group
// +k8s:deepcopy-gen=package,register
// +groupName=gate.xdmybl.io
package v1
