// Code generated by protoc-gen-ext. DO NOT EDIT.
// source: github.com/xdmybl/gate-type/proto/gate/v1/filter.proto

package v1

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"strings"

	"github.com/golang/protobuf/proto"
	equality "github.com/solo-io/protoc-gen-ext/pkg/equality"
)

// ensure the imports are used
var (
	_ = errors.New("")
	_ = fmt.Print
	_ = binary.LittleEndian
	_ = bytes.Compare
	_ = strings.Compare
	_ = equality.Equalizer(nil)
	_ = proto.Message(nil)
)

// Equal function
func (m *FilterSpec) Equal(that interface{}) bool {
	if that == nil {
		return m == nil
	}

	target, ok := that.(*FilterSpec)
	if !ok {
		that2, ok := that.(FilterSpec)
		if ok {
			target = &that2
		} else {
			return false
		}
	}
	if target == nil {
		return m == nil
	} else if m == nil {
		return false
	}

	if h, ok := interface{}(m.GetCommonInfo()).(equality.Equalizer); ok {
		if !h.Equal(target.GetCommonInfo()) {
			return false
		}
	} else {
		if !proto.Equal(m.GetCommonInfo(), target.GetCommonInfo()) {
			return false
		}
	}

	switch m.FilterType.(type) {

	case *FilterSpec_Hcm:
		if _, ok := target.FilterType.(*FilterSpec_Hcm); !ok {
			return false
		}

		if h, ok := interface{}(m.GetHcm()).(equality.Equalizer); ok {
			if !h.Equal(target.GetHcm()) {
				return false
			}
		} else {
			if !proto.Equal(m.GetHcm(), target.GetHcm()) {
				return false
			}
		}

	case *FilterSpec_TcpProxy:
		if _, ok := target.FilterType.(*FilterSpec_TcpProxy); !ok {
			return false
		}

		if h, ok := interface{}(m.GetTcpProxy()).(equality.Equalizer); ok {
			if !h.Equal(target.GetTcpProxy()) {
				return false
			}
		} else {
			if !proto.Equal(m.GetTcpProxy(), target.GetTcpProxy()) {
				return false
			}
		}

	default:
		// m is nil but target is not nil
		if m.FilterType != target.FilterType {
			return false
		}
	}

	return true
}

// Equal function
func (m *HttpConnectionManager) Equal(that interface{}) bool {
	if that == nil {
		return m == nil
	}

	target, ok := that.(*HttpConnectionManager)
	if !ok {
		that2, ok := that.(HttpConnectionManager)
		if ok {
			target = &that2
		} else {
			return false
		}
	}
	if target == nil {
		return m == nil
	} else if m == nil {
		return false
	}

	if strings.Compare(m.GetRouteConfigName(), target.GetRouteConfigName()) != 0 {
		return false
	}

	if len(m.GetHttpFilter()) != len(target.GetHttpFilter()) {
		return false
	}
	for idx, v := range m.GetHttpFilter() {

		if h, ok := interface{}(v).(equality.Equalizer); ok {
			if !h.Equal(target.GetHttpFilter()[idx]) {
				return false
			}
		} else {
			if !proto.Equal(v, target.GetHttpFilter()[idx]) {
				return false
			}
		}

	}

	if m.GetMergeSlashes() != target.GetMergeSlashes() {
		return false
	}

	if m.GetSkipXffAppend() != target.GetSkipXffAppend() {
		return false
	}

	return true
}

// Equal function
func (m *HttpFilter) Equal(that interface{}) bool {
	if that == nil {
		return m == nil
	}

	target, ok := that.(*HttpFilter)
	if !ok {
		that2, ok := that.(HttpFilter)
		if ok {
			target = &that2
		} else {
			return false
		}
	}
	if target == nil {
		return m == nil
	} else if m == nil {
		return false
	}

	return true
}

// Equal function
func (m *TcpProxy) Equal(that interface{}) bool {
	if that == nil {
		return m == nil
	}

	target, ok := that.(*TcpProxy)
	if !ok {
		that2, ok := that.(TcpProxy)
		if ok {
			target = &that2
		} else {
			return false
		}
	}
	if target == nil {
		return m == nil
	} else if m == nil {
		return false
	}

	return true
}
