// Code generated by engine gate build no edit

// This file contains generated Deepcopy methods for proto-based Spec and Status fields

package v1

import (
	proto "github.com/golang/protobuf/proto"
	"github.com/solo-io/protoc-gen-ext/pkg/clone"
)

// DeepCopyInto for the CaCertificate.Spec
func (in *CaCertificateSpec) DeepCopyInto(out *CaCertificateSpec) {
	var p *CaCertificateSpec
	if h, ok := interface{}(in).(clone.Cloner); ok {
		p = h.Clone().(*CaCertificateSpec)
	} else {
		p = proto.Clone(in).(*CaCertificateSpec)
	}
	*out = *p
}

// DeepCopyInto for the Certificate.Spec
func (in *CertificateSpec) DeepCopyInto(out *CertificateSpec) {
	var p *CertificateSpec
	if h, ok := interface{}(in).(clone.Cloner); ok {
		p = h.Clone().(*CertificateSpec)
	} else {
		p = proto.Clone(in).(*CertificateSpec)
	}
	*out = *p
}

// DeepCopyInto for the Upstream.Spec
func (in *UpstreamSpec) DeepCopyInto(out *UpstreamSpec) {
	var p *UpstreamSpec
	if h, ok := interface{}(in).(clone.Cloner); ok {
		p = h.Clone().(*UpstreamSpec)
	} else {
		p = proto.Clone(in).(*UpstreamSpec)
	}
	*out = *p
}

// DeepCopyInto for the Gateway.Spec
func (in *GatewaySpec) DeepCopyInto(out *GatewaySpec) {
	var p *GatewaySpec
	if h, ok := interface{}(in).(clone.Cloner); ok {
		p = h.Clone().(*GatewaySpec)
	} else {
		p = proto.Clone(in).(*GatewaySpec)
	}
	*out = *p
}

// DeepCopyInto for the Filter.Spec
func (in *FilterSpec) DeepCopyInto(out *FilterSpec) {
	var p *FilterSpec
	if h, ok := interface{}(in).(clone.Cloner); ok {
		p = h.Clone().(*FilterSpec)
	} else {
		p = proto.Clone(in).(*FilterSpec)
	}
	*out = *p
}
