// Code generated by engine gate build no edit

// Definitions for the Kubernetes types
package v1

import ()

// CaCertificateSlice represents a slice of *CaCertificate
type CaCertificateSlice []*CaCertificate

// CertificateSlice represents a slice of *Certificate
type CertificateSlice []*Certificate

// UpstreamSlice represents a slice of *Upstream
type UpstreamSlice []*Upstream

// GatewaySlice represents a slice of *Gateway
type GatewaySlice []*Gateway

// FilterSlice represents a slice of *Filter
type FilterSlice []*Filter
