// Code generated by engine gate build no edit

//go:generate mockgen -source ./multicluster_reconcilers.go -destination mocks/multicluster_reconcilers.go

// Definitions for the multicluster Kubernetes Controllers
package controller

import (
	"context"

	gate_v1 "github.com/xdmybl/gate-type/pkg/api/gate/v1"

	"github.com/pkg/errors"
	"github.com/solo-io/skv2/pkg/ezkube"
	"github.com/solo-io/skv2/pkg/multicluster"
	mc_reconcile "github.com/solo-io/skv2/pkg/multicluster/reconcile"
	"github.com/solo-io/skv2/pkg/reconcile"
	"sigs.k8s.io/controller-runtime/pkg/predicate"
)

// Reconcile Upsert events for the CaCertificate Resource across clusters.
// implemented by the user
type MulticlusterCaCertificateReconciler interface {
	ReconcileCaCertificate(clusterName string, obj *gate_v1.CaCertificate) (reconcile.Result, error)
}

// Reconcile deletion events for the CaCertificate Resource across clusters.
// Deletion receives a reconcile.Request as we cannot guarantee the last state of the object
// before being deleted.
// implemented by the user
type MulticlusterCaCertificateDeletionReconciler interface {
	ReconcileCaCertificateDeletion(clusterName string, req reconcile.Request) error
}

type MulticlusterCaCertificateReconcilerFuncs struct {
	OnReconcileCaCertificate         func(clusterName string, obj *gate_v1.CaCertificate) (reconcile.Result, error)
	OnReconcileCaCertificateDeletion func(clusterName string, req reconcile.Request) error
}

func (f *MulticlusterCaCertificateReconcilerFuncs) ReconcileCaCertificate(clusterName string, obj *gate_v1.CaCertificate) (reconcile.Result, error) {
	if f.OnReconcileCaCertificate == nil {
		return reconcile.Result{}, nil
	}
	return f.OnReconcileCaCertificate(clusterName, obj)
}

func (f *MulticlusterCaCertificateReconcilerFuncs) ReconcileCaCertificateDeletion(clusterName string, req reconcile.Request) error {
	if f.OnReconcileCaCertificateDeletion == nil {
		return nil
	}
	return f.OnReconcileCaCertificateDeletion(clusterName, req)
}

type MulticlusterCaCertificateReconcileLoop interface {
	// AddMulticlusterCaCertificateReconciler adds a MulticlusterCaCertificateReconciler to the MulticlusterCaCertificateReconcileLoop.
	AddMulticlusterCaCertificateReconciler(ctx context.Context, rec MulticlusterCaCertificateReconciler, predicates ...predicate.Predicate)
}

type multiclusterCaCertificateReconcileLoop struct {
	loop multicluster.Loop
}

func (m *multiclusterCaCertificateReconcileLoop) AddMulticlusterCaCertificateReconciler(ctx context.Context, rec MulticlusterCaCertificateReconciler, predicates ...predicate.Predicate) {
	genericReconciler := genericCaCertificateMulticlusterReconciler{reconciler: rec}

	m.loop.AddReconciler(ctx, genericReconciler, predicates...)
}

func NewMulticlusterCaCertificateReconcileLoop(name string, cw multicluster.ClusterWatcher, options reconcile.Options) MulticlusterCaCertificateReconcileLoop {
	return &multiclusterCaCertificateReconcileLoop{loop: mc_reconcile.NewLoop(name, cw, &gate_v1.CaCertificate{}, options)}
}

type genericCaCertificateMulticlusterReconciler struct {
	reconciler MulticlusterCaCertificateReconciler
}

func (g genericCaCertificateMulticlusterReconciler) ReconcileDeletion(cluster string, req reconcile.Request) error {
	if deletionReconciler, ok := g.reconciler.(MulticlusterCaCertificateDeletionReconciler); ok {
		return deletionReconciler.ReconcileCaCertificateDeletion(cluster, req)
	}
	return nil
}

func (g genericCaCertificateMulticlusterReconciler) Reconcile(cluster string, object ezkube.Object) (reconcile.Result, error) {
	obj, ok := object.(*gate_v1.CaCertificate)
	if !ok {
		return reconcile.Result{}, errors.Errorf("internal error: CaCertificate handler received event for %T", object)
	}
	return g.reconciler.ReconcileCaCertificate(cluster, obj)
}

// Reconcile Upsert events for the SslCertificate Resource across clusters.
// implemented by the user
type MulticlusterSslCertificateReconciler interface {
	ReconcileSslCertificate(clusterName string, obj *gate_v1.SslCertificate) (reconcile.Result, error)
}

// Reconcile deletion events for the SslCertificate Resource across clusters.
// Deletion receives a reconcile.Request as we cannot guarantee the last state of the object
// before being deleted.
// implemented by the user
type MulticlusterSslCertificateDeletionReconciler interface {
	ReconcileSslCertificateDeletion(clusterName string, req reconcile.Request) error
}

type MulticlusterSslCertificateReconcilerFuncs struct {
	OnReconcileSslCertificate         func(clusterName string, obj *gate_v1.SslCertificate) (reconcile.Result, error)
	OnReconcileSslCertificateDeletion func(clusterName string, req reconcile.Request) error
}

func (f *MulticlusterSslCertificateReconcilerFuncs) ReconcileSslCertificate(clusterName string, obj *gate_v1.SslCertificate) (reconcile.Result, error) {
	if f.OnReconcileSslCertificate == nil {
		return reconcile.Result{}, nil
	}
	return f.OnReconcileSslCertificate(clusterName, obj)
}

func (f *MulticlusterSslCertificateReconcilerFuncs) ReconcileSslCertificateDeletion(clusterName string, req reconcile.Request) error {
	if f.OnReconcileSslCertificateDeletion == nil {
		return nil
	}
	return f.OnReconcileSslCertificateDeletion(clusterName, req)
}

type MulticlusterSslCertificateReconcileLoop interface {
	// AddMulticlusterSslCertificateReconciler adds a MulticlusterSslCertificateReconciler to the MulticlusterSslCertificateReconcileLoop.
	AddMulticlusterSslCertificateReconciler(ctx context.Context, rec MulticlusterSslCertificateReconciler, predicates ...predicate.Predicate)
}

type multiclusterSslCertificateReconcileLoop struct {
	loop multicluster.Loop
}

func (m *multiclusterSslCertificateReconcileLoop) AddMulticlusterSslCertificateReconciler(ctx context.Context, rec MulticlusterSslCertificateReconciler, predicates ...predicate.Predicate) {
	genericReconciler := genericSslCertificateMulticlusterReconciler{reconciler: rec}

	m.loop.AddReconciler(ctx, genericReconciler, predicates...)
}

func NewMulticlusterSslCertificateReconcileLoop(name string, cw multicluster.ClusterWatcher, options reconcile.Options) MulticlusterSslCertificateReconcileLoop {
	return &multiclusterSslCertificateReconcileLoop{loop: mc_reconcile.NewLoop(name, cw, &gate_v1.SslCertificate{}, options)}
}

type genericSslCertificateMulticlusterReconciler struct {
	reconciler MulticlusterSslCertificateReconciler
}

func (g genericSslCertificateMulticlusterReconciler) ReconcileDeletion(cluster string, req reconcile.Request) error {
	if deletionReconciler, ok := g.reconciler.(MulticlusterSslCertificateDeletionReconciler); ok {
		return deletionReconciler.ReconcileSslCertificateDeletion(cluster, req)
	}
	return nil
}

func (g genericSslCertificateMulticlusterReconciler) Reconcile(cluster string, object ezkube.Object) (reconcile.Result, error) {
	obj, ok := object.(*gate_v1.SslCertificate)
	if !ok {
		return reconcile.Result{}, errors.Errorf("internal error: SslCertificate handler received event for %T", object)
	}
	return g.reconciler.ReconcileSslCertificate(cluster, obj)
}
